# Q3. Singular Value Decomposition (SVD):
Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print matrices U, Σ, and V.Verify that A equals the product of U, Σ, and 𝑉. Additionally, find the rank 2 and rank 3 approximations of matrix A.

In [1]:
import numpy as np
np.random.seed(40)
A = np.random.randint(0, 10, size=(5, 5))

In [2]:
# Perform Singular Value Decomposition (SVD)
U,Sigma,V_transpose = np.linalg.svd(A)
Sigma_mat = np.zeros_like(A, dtype=float)
Sigma_mat[:min(A.shape[0], A.shape[1]), :min(A.shape[0], A.shape[1])] = np.diag(Sigma)
print("Matrix U:")
print(U)
print("\nMatrix Sigma:")
print(Sigma_mat)
print("\nMatrix V:")
print(V_transpose.T)

Matrix U:
[[-0.55617931 -0.4941492  -0.29709013 -0.28075548  0.52857824]
 [-0.26157381  0.34010041 -0.43410466 -0.59834228 -0.51908623]
 [-0.37276093  0.72624079  0.35644906 -0.07214716  0.44873428]
 [-0.52156941  0.1152339  -0.33382271  0.74009572 -0.23559971]
 [-0.45962849 -0.31534701  0.6962737  -0.10107421 -0.44077756]]

Matrix Sigma:
[[26.41173173  0.          0.          0.          0.        ]
 [ 0.          8.65687304  0.          0.          0.        ]
 [ 0.          0.          4.89467506  0.          0.        ]
 [ 0.          0.          0.          3.92849576  0.        ]
 [ 0.          0.          0.          0.          1.44500974]]

Matrix V:
[[-0.48290756  0.09846333  0.76521307 -0.12584018  0.3946118 ]
 [-0.48179376 -0.20737264 -0.05539706  0.83348545 -0.16463453]
 [-0.51182567  0.74183301 -0.38774839 -0.15882789 -0.11019598]
 [-0.3194696  -0.43411729 -0.50900215 -0.19996666  0.64063368]
 [-0.4130965  -0.45664815  0.04413757 -0.47355389 -0.62818973]]


In [3]:
A_reconstructed = np.dot(U, np.dot(Sigma_mat, V_transpose))
print("Verification that A equals the product of U, Sigma, and V:")
print(np.allclose(A, A_reconstructed))

Verification that A equals the product of U, Sigma, and V:
True
